// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const SquareVerifier = artifacts.require('./Verifier');
const Proof = require('../../zokrates/code/square/proof.json');

// Test verification with correct proof
contract('SquareVerifier', accounts => {

    describe('zK-SNARKS VALIDATION PROOF', function () {
        beforeEach(async () => {
            this.contract = await Verifier.new();
        });
    })


// - use the contents from proof.json generated from zokrates steps
it('VALIDATE CORRECT PROOF', async () => {
    let verified = await this.contract.verifyTx(Proof.proof, Proof.inputs)
    assert.equal(verified, true);
})

    
// Test verification with incorrect proof
it('VALIDATE PROOF IS NOT CORRECT', async () => {
    let verified = await this.contract.verifyTx(Proof.proof, [1, 3]);
    assert.equal(verified, false);
})

});
